fixing empty variable execution bug

diff --git a/lib/func_and_vars/logs_functions b/lib/func_and_vars/logs_functions
--- a/lib/func_and_vars/logs_functions
+++ b/lib/func_and_vars/logs_functions
@@ -3,9 +3,10 @@
 ## logs management functions
 #<start>
 show_logs(){
-	if [[ "$CONFIG_FILE_location" == "" ]]; then
+	if [[ "$GIT_MAIN_FOLDER_location" == "" ]]; then
 		if [[ ! -d "$SCRIPT_LOCATION"/lib/logs ]]; then
-			echo "${YELLLOW}[-]${WHITE} There is nothing being logged, what do you even wanna see ¯\_(ツ)_/¯"
+			echo
+			echo "${YELLOW}[-]${WHITE} There is nothing being logged, what do you even wanna see ¯\_(ツ)_/¯"
 			_EXIT_
 		fi
 
@@ -61,17 +62,17 @@ show_logs(){
 }
 
 clear_logs(){
-	if [[ $CONFIG_FILE_location == "all" ]]; then
+	if [[ $GIT_MAIN_FOLDER_location == "all" ]]; then
 		if [[ -d "$SCRIPT_LOCATION"/lib/logs ]]; then
 			rm -r "$SCRIPT_LOCATION"/lib/logs/ && echo "${GREEN}[+] ${WHITE}Logs folder deleted successfully" || echo "${RED}[!]${WHITE} There was an error while deleting the log folder"
 		else
 			echo "${YELLOW}[-]${WHITE} Logs folder has been deleted already"
 		fi
-	elif [[ $CONFIG_FILE_location == "" ]]; then
-		echo "${RED}[!]${WHITE} Specify the config file (${CYAN}name${WHITE}/${CYAN}full path${WHITE}) with ${CYAN}-c${WHITE} argument"
+	elif [[ $GIT_MAIN_FOLDER_location == "" ]]; then
+		echo "${RED}[!]${WHITE} Specify the config containing folder (${CYAN}name${WHITE}/${CYAN}full path${WHITE}) with ${CYAN}-g${WHITE} argument"
 	else
 		if [[ -f "$SCRIPT_LOCATION"/lib/logs/"$GIT_MAIN_FOLDER".log ]]; then
-			rm "$SCRIPT_LOCATION"/lib/logs/"$GIT_MAIN_FOLDER".log && echo "${GREEN}[+] ${WHITE}Logs for the specified file are deleted successfully" || echo "${RED}[!]${WHITE} There was an error while deleting the logs for specified file"
+			rm "$SCRIPT_LOCATION"/lib/logs/"$GIT_MAIN_FOLDER".log && echo "${GREEN}[+] ${WHITE}Logs for the specified folder are deleted successfully" || echo "${RED}[!]${WHITE} There was an error while deleting the logs for the specified folder"
 		else
 			echo "${YELLOW}[-]${WHITE} Logs for this config folder have been deleted already"
 		fi
diff --git a/lib/func_and_vars/service_functions b/lib/func_and_vars/service_functions
--- a/lib/func_and_vars/service_functions
+++ b/lib/func_and_vars/service_functions
@@ -79,12 +79,12 @@ service_start(){
 					if [[ ${ENTRY_FOUND[$i]} == 0 ]]; then
 						START_SERVICE=$(awk "NR==$((7+i)){print}" "$STARTUP_SCRIPT")
 						eval "$START_SERVICE"
-						echo "  [${GREEN}STARTED${WHITE}] "
+						echo " [${GREEN}STARTED${WHITE}] "
 					fi
 				done
 			fi
 		else
-			"$STARTUP_SCRIPT" && echo -e " [${GREEN}STARTED${WHITE}]" || echo -e " [${RED}FAILED TO START${WHITE}]"
+			/bin/bash "$STARTUP_SCRIPT" && echo -e " [${GREEN}STARTED${WHITE}]" || echo -e " [${RED}FAILED TO START${WHITE}]"
 		fi
 		echo
 	fi
@@ -92,24 +92,15 @@ service_start(){
 
 service_stop(){
 	SERVICE_COUNT=$(ps -ef | grep "$SYNC_SCRIPT_location" | awk '{print $2}' | grep "^" -c)
-	_=$(( GINDEX = 1 ))
 	echo
-	for ((i=SERVICE_COUNT; i>1; i--))
+	for (( i=SERVICE_COUNT; i>1; i-- ))
 	do
 		PID=$(ps -ef | grep "$SYNC_SCRIPT_location" | awk 'NR==1{print $2}')
-		GIT_MAIN_FOLDER_location=$(ps -ef | grep "$SYNC_SCRIPT_location" | awk "NR==${GINDEX}{print \$11}")
+		GIT_MAIN_FOLDER_location=$(ps -ef | grep "$SYNC_SCRIPT_location" | awk "NR==1{print \$11}")
+		GIT_MAIN_FOLDER="${GIT_MAIN_FOLDER_location##*/}"
 		kill "$PID"
 		## Appending the termination message into the logs
-		## will give one more than the actual number of config files
-		CONFIG_COUNT=$(find "$GIT_MAIN_FOLDER_location" ! \( -name . -o -name .. -o -name .git -o -name README.md -o -name .gsync_init -o -name .gitignore \) -maxdepth 1 | grep -e "^" -c)
-		_=$(( CINDEX = 2 ))
-		for (( j=CONFIG_COUNT; j>1; j-- ))
-		do
-			CONFIG_FILE=$(find "$GIT_MAIN_FOLDER_location" ! \( -name . -o -name .. -o -name .git -o -name README.md -o -name .gsync_init -o -name .gitignore \) -maxdepth 1 | awk "NR==${CINDEX}{print \$1}")
-			CONFIG_FILE=${CONFIG_FILE##*/}
-			echo "[${YELLOW}$(date)${WHITE}] [${RED}KILL${WHITE}] Terminated process runnning on PID=${CYAN}$PID${WHITE}" >> "$SCRIPT_LOCATION"/lib/logs/"$CONFIG_FILE".log
-			_=$(( CINDEX = CINDEX + 1 ))
-		done
+		echo "[${YELLOW}$(date)${WHITE}] [${RED}KILL${WHITE}] Terminated process runnning on PID=${CYAN}$PID${WHITE}" >> "$SCRIPT_LOCATION"/lib/logs/"$GIT_MAIN_FOLDER".log
 	done
 	if [[ $SERVICE_COUNT == 1 ]]; then
 		echo -e " STATUS: [${RED}NOT RUNNING${WHITE}]"
