runs gsync start command on login: more robust service management

diff --git a/lib/func_and_vars/service_functions b/lib/func_and_vars/service_functions
--- a/lib/func_and_vars/service_functions
+++ b/lib/func_and_vars/service_functions
@@ -16,7 +16,7 @@ service_status() {
 	fi
 	SERVICE_COUNT=$(ps -ef | grep "$SYNC_SCRIPT_location" | awk '{print $2}' | grep "^" -c)
 	_=$(( SERVICE_COUNT = SERVICE_COUNT - 1 ))
-	ENTRY_COUNT=$(grep "$STARTUP_SCRIPT" -ce "-d")
+	ENTRY_COUNT=$(grep "$SERVICES_SCRIPT" -ce "-d")
 	echo
 	if [[ $SERVICE_COUNT == 0 ]]; then
 		echo -e " STATUS: [${RED}NOT RUNNING${WHITE}]  STARTUP SERVICE: [$STARTUP_STATUS]
@@ -50,7 +50,7 @@ service_status() {
 	_=$(( k = 0 ))
 	for (( i=ENTRY_COUNT; i>0; i-- ))
 	do
-		ENTRY=$(awk "NR==${AINDEX}{print \$4}" "$STARTUP_SCRIPT")
+		ENTRY=$(awk "NR==${AINDEX}{print \$4}" "$SERVICES_SCRIPT")
 		_=$(( PINDEX = 1 ))
 		for (( j=SERVICE_COUNT; j>0; j-- ))
 		do
@@ -78,7 +78,7 @@ service_status() {
 }
 
 service_start(){
-	if [[ ! -f $STARTUP_SCRIPT ]]; then
+	if [[ ! -f $SERVICES_SCRIPT ]]; then
 		echo "${RED}[!]${WHITE} No service(s) available currently to start"
 		_EXIT_
 	else
@@ -90,8 +90,9 @@ service_start(){
 		SERVICE_COUNT=$(ps -ef | grep "$SYNC_SCRIPT_location" | awk '{print $2}' | grep "^" -c)
 		echo
 		if [[ $SERVICE_COUNT != 1 ]]; then
-			## Matching with entries in startup script
-			ENTRY_COUNT=$(grep "$STARTUP_SCRIPT" -ce "-d")
+			## Starting only those services which are not already running
+			## Matching with entries in services script
+			ENTRY_COUNT=$(grep "$SERVICES_SCRIPT" -ce "-d")
 			if [[ $((SERVICE_COUNT - 1)) == "$ENTRY_COUNT" ]]; then
 				echo -e " STATUS: [${GREEN}RUNNING${WHITE}]"
 			else
@@ -105,7 +106,7 @@ service_start(){
 				_=$(( k = 0 ))
 				for (( i=ENTRY_COUNT; i>0; i-- ))
 				do
-					ENTRY=$(awk "NR==${AINDEX}{print \$4}" "$STARTUP_SCRIPT")
+					ENTRY=$(awk "NR==${AINDEX}{print \$4}" "$SERVICES_SCRIPT")
 					_=$(( PINDEX = 1 ))
 					for (( j=SERVICE_COUNT; j>1; j-- ))
 					do
@@ -123,14 +124,14 @@ service_start(){
 				for (( i=0; i<ENTRY_COUNT; i++ ))
 				do
 					if [[ ${ENTRY_FOUND[$i]} == 0 ]]; then
-						START_SERVICE=$(awk "NR==$((7+i)){print}" "$STARTUP_SCRIPT")
+						START_SERVICE=$(awk "NR==$((7+i)){print}" "$SERVICES_SCRIPT")
 						eval "$START_SERVICE"
-						echo " [${GREEN}STARTED${WHITE}] "
 					fi
 				done
+				echo " [${GREEN}STARTED${WHITE}] "
 			fi
 		else
-			/bin/bash "$STARTUP_SCRIPT" && echo -e " [${GREEN}STARTED${WHITE}]" || echo -e " [${RED}FAILED TO START${WHITE}]"
+			/bin/bash "$SERVICES_SCRIPT" && echo -e " [${GREEN}STARTED${WHITE}]" || echo -e " [${RED}FAILED TO START${WHITE}]"
 		fi
 		echo
 	fi
@@ -162,7 +163,7 @@ service_restart(){
 }
 
 service_enable() {
-		## implementing logic for executing the startup script on every login
+		## implementing logic for executing the services script on every login
 		if [[ $KERNEL == "Darwin" ]]; then
 			## giving /bin/bash full disk access if not given already
 			BINBASH_CHECK=$(sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db 'select client from access where auth_value and service = "kTCCServiceSystemPolicyAllFiles"' | grep -iq "/bin/bash" && echo 1)
@@ -205,7 +206,6 @@ service_enable() {
 				fi
 			fi
 
-
 			echo
 			if [[ ! -f ~/Library/LaunchAgents/com.gsync-startup.plist ]]; then
 				## Method used for starting the startup.sh script on login: LaunchAgent
@@ -246,9 +246,8 @@ service_enable() {
 			echo
 		else
 			## Method used for starting the startup.sh script on login: /etc/profile.d
-			MODFIED=$(diff /etc/profile.d/gsync-startup.sh "$STARTUP_SCRIPT")
 			echo
-			if [[ $MODFIED != "" ]]; then
+			if [[ ! -f /etc/profile.d/gsync-startup.sh ]]; then
 				cp "$STARTUP_SCRIPT" /etc/profile.d/gsync-startup.sh && echo -e "  STARTUP SERVICE: [${GREEN}ENABLED${WHITE}]" || echo -e "  STARTUP SERVICE: [${RED}DISABLED${WHITE}]"
 			else
 				echo -e "  STARTUP SERVICE: [${GREEN}ENABLED${WHITE}]"
